/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Clases_Auxiliares.ComponentListHelp;
import Clases_Auxiliares.Conexion;
import Clases_Auxiliares.Validaciones;
import java.awt.Component;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Manolo
 */
public class GUI_A_Articulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_A_Articulo
     */
    private ComponentListHelp rc = new ComponentListHelp();
    private Conexion r_con = new Conexion();
    private ArrayList<String> items = new ArrayList<String>();
    private int usuario;
    
    public GUI_A_Articulo(int u) {
        initComponents();
        r_con.Connection();
        prepararHelp();
        usuario=u;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setIconifiable(true);
        setTitle("Articulo.");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/articulo.png"))); // NOI18N
        setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Artículo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Código:");

        jTextField1.setToolTipText("");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Descripción:");

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Proveedor:");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Precio $:");

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Stock:");

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Código de tasa de IVA:");

        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField6FocusLost(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel8.setText("-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Nombre de tasa de IVA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField6)
                    .addComponent(jTextField2))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void prepararHelp(){
        rc.convertirComponente(jTextField6);       
        ResultSet rs = r_con.Consultar("SELECT * FROM Tasas_IVA");        
        items.add("");
        try {
            while (rs.next())
            {
                String nue = (rs.getString(1)+" - "+rs.getString(2));
                items.add(nue);
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_A_Articulo.class.getName()).log(Level.SEVERE, null, ex);
        }
        rc.asignarLista(jTextField6, items);
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        r_con.cierraConexion();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean camposNecesarios () {
        if ((jTextField1.getText().length()==0) ||
            (jTextField2.getText().length()==0) ||
            (jTextField3.getText().length()==0) ||
            (jTextField4.getText().length()==0) ||
            (jTextField5.getText().length()==0) ||
            (jTextField6.getText().length()==0))
        {
            JOptionPane.showMessageDialog(null, "Complete todos los campos!","Atención",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        if (("Aceptar".equals(this.jButton2.getText())) && (camposNecesarios())){
            r_con = new Conexion();
            r_con.Connection();
 
            String sql = "INSERT INTO Articulos "
                        + "VALUES('"+jTextField1.getText()+"','"
                                    +jTextField2.getText()+"','"
                                    +jTextField3.getText()+"',"
                                    +Float.parseFloat(jTextField4.getText())+","
                                    +Integer.parseInt(jTextField5.getText())+",'"
                                    +jTextField6.getText()+"')";
            //r_con.Insertar(sql);
            if (r_con.Insertar(sql)){
                // para auditoria
                
                InetAddress addr;
                String terminal="";
                try { 
                    addr = InetAddress.getLocalHost();
                    terminal = addr.getHostName(); 
                } catch (UnknownHostException ex) {
                    Logger.getLogger(GUI_A_Articulo.class.getName()).log(Level.SEVERE, null, ex);
                }            
                SimpleDateFormat formatEntrada = new SimpleDateFormat("yyyy-MM-dd kk:mm:ss.S"); 
                Date fechaEntrada = new Date(); 
                String fecha = formatEntrada.format(fechaEntrada); 

                Vector<Vector<String>>v = r_con.getContenidoTabla("select * from auditoria_articulo");
                int cant=v.size()+1;                        

                sql="insert into auditoria_articulo values("+cant+","+usuario+","+1+","+1+",'"+fecha+"','"+terminal+"','"+
                                        jTextField1.getText()+"','"+
                                        jTextField2.getText()+"','"+
                                        jTextField3.getText()+"',"
                                        +Float.parseFloat(jTextField4.getText())+","
                                        +Integer.parseInt(jTextField5.getText())+",'"
                                        +jTextField6.getText()+"')";                        
                System.out.println(sql);
                r_con.Insertar(sql);
                limpiarForm();
            }
            r_con.cierraConexion();
            
        }
        else{
            if (("Buscar".equals(this.jButton2.getText()))){
                
                boolean existe = false;
                r_con = new Conexion();
                r_con.Connection();
                ResultSet rs = r_con.Consultar("SELECT * FROM Articulos WHERE art_codigo = '"+jTextField1.getText()+"'");
                try {
                     
                     while (rs.next())
                    {     
                        if ("Baja Artículo:".equals(jLabel1.getText())){
                            jTextField1.setEnabled(false);
                        }
                        if ("Modificación Artículo:".equals(jLabel1.getText())){
                            this.form_Complete();
                        }
                        if ("Consulta Artículo:".equals(jLabel1.getText())){
                            this.form_Complete();
                        }
                      
                        jTextField2.setText(rs.getString(2));
                        jTextField3.setText(rs.getString(3));
                        jTextField4.setText(rs.getString(4));
                        jTextField5.setText(rs.getString(5));
                        jTextField6.setText(rs.getString(6));
                        muestraValor(jTextField6.getText());
                        
                        existe = true;
                    } 
                } catch (SQLException ex) {

                    Logger.getLogger(GUI_A_Articulo.class.getName()).log(Level.SEVERE, null, ex);
                }
                r_con.cierraConexion();
                if (!existe){
                    jTextField1.setEnabled(true);
                    jTextField1.requestFocus();
                    jTextField1.selectAll();
                    JOptionPane.showMessageDialog(null, "El Articulo "+jTextField1.getText()+" no se encuentra registrado.","Cuidado",JOptionPane.WARNING_MESSAGE);
                }
                else{
                    if ("Baja Artículo:".equals(jLabel1.getText())){
                        buttonEliminar ();
                     }
                     if ("Modificación Artículo:".equals(jLabel1.getText())){
                        buttonModificar ();
                     }
                     if ("Consulta Artículo:".equals(jLabel1.getText())){
                         buttonNuevaConsulta();
                     }
                     
                }
            }
            else{
                if (("Eliminar".equals(this.jButton2.getText()))){               
                r_con = new Conexion();
                r_con.Connection();
                r_con.Borrar("DELETE FROM Articulos WHERE art_codigo = '"+jTextField1.getText()+"'");

                // para auditoria
                
                InetAddress addr;
                String terminal="";
                try { 
                    addr = InetAddress.getLocalHost();
                    terminal = addr.getHostName(); 
                } catch (UnknownHostException ex) {
                    Logger.getLogger(GUI_A_Articulo.class.getName()).log(Level.SEVERE, null, ex);
                }           
                SimpleDateFormat formatEntrada = new SimpleDateFormat("yyyy-MM-dd kk:mm:ss.S"); 
                Date fechaEntrada = new Date(); 
                String fecha = formatEntrada.format(fechaEntrada); 

                Vector<Vector<String>>v = r_con.getContenidoTabla("select * from auditoria_articulo");
                int cant=v.size()+1;                        

                String  sql="insert into auditoria_articulo values("+cant+","+usuario+","+1+","+2+",'"+fecha+"','"+terminal+"','"+
                                        jTextField1.getText()+"','"+
                                        jTextField2.getText()+"','"+
                                        jTextField3.getText()+"',"
                                        +Float.parseFloat(jTextField4.getText())+","
                                        +Integer.parseInt(jTextField5.getText())+",'"
                                        +jTextField6.getText()+"')"; 
                                                               
                System.out.println(sql);
                r_con.Insertar(sql);
                limpiarForm();                
                r_con.cierraConexion();               
                this.dispose();
                }
                else{
                     if (("Nueva Consulta".equals(this.jButton2.getText()))){
                        this.limpiarForm();
                        form_onlySearch();
                        buttonBuscar();
                     }
                     else{
                         if (("Modificar".equals(this.jButton2.getText()))&& (camposNecesarios())){
                                    r_con = new Conexion();
                                    r_con.Connection();

                                    
                                    String sql =  "UPDATE Articulos SET "
                                                + "art_desc = '"+jTextField2.getText()+"', "
                                                + "art_proveedor = '"+jTextField3.getText()+"', "
                                                + "art_precio = '"+Float.parseFloat(jTextField4.getText())+"', "
                                                + "art_stock = '"+Integer.parseInt(jTextField5.getText())+"', "
                                                + "art_cod_tasa_iva = '"+jTextField6.getText()+"' WHERE "
                                                + "art_codigo = '"+jTextField1.getText()+"';";
                                    if (r_con.Actualizar(sql)){
                                        limpiarForm();
                                        form_onlySearch();        
                                        buttonBuscar();
                                    }
                                    r_con.cierraConexion();

                             
                         }
                     }
                }
            }
          
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarMSSG (Component c){
        KeyEvent ke = new KeyEvent(c, KeyEvent.KEY_PRESSED,
        System.currentTimeMillis(), InputEvent.CTRL_MASK, KeyEvent.VK_F1, KeyEvent.CHAR_UNDEFINED);
        c.dispatchEvent(ke);
    }
    
    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField2.getText());
        cad = v.soloPrimerMayus(cad);
        if ((cad.length()<=25)) {
            jTextField2.setText(cad);
            jTextField2.setToolTipText("campo correcto.");
        }
        else{
            jTextField2.requestFocus();
            jTextField2.selectAll();
            jTextField2.setToolTipText("longitud maxima 25 caracteres.");              
            mostrarMSSG(evt.getComponent());
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField3.getText());
        cad = v.soloPrimerMayus(cad);
        if ((cad.length()<=15)) {
            jTextField3.setText(cad);
            jTextField3.setToolTipText("campo correcto.");
        }
        else{
            jTextField3.requestFocus();
            jTextField3.selectAll();
            jTextField3.setToolTipText("longitud maxima 15 caracteres.");              
            mostrarMSSG(evt.getComponent());
        }
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField4.getText());
        if (cad.length()!=0){
            if ((v.isFloat(cad))&& (cad.length()<=12)){
                jTextField4.setToolTipText("campo correcto.");
            }
            else{
                jTextField4.requestFocus();
                jTextField4.selectAll();
                if (cad.length()>12) {
                    jTextField5.setToolTipText("longitud maxima del campo 12 caracteres.");
                }
                else{           
                    jTextField4.setToolTipText("debe ingresar un NÚMERO ej: 10.10");
                }           
                mostrarMSSG(evt.getComponent());
            }
       }
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField1.getText());
        cad = v.soloPrimerMayus(cad);
        if ((cad.length()<=15)) {
            jTextField1.setText(cad);
            jTextField1.setToolTipText("campo correcto.");
        }
        else{
            jTextField1.requestFocus();
            jTextField1.selectAll();
            jTextField1.setToolTipText("longitud maxima 15 caracteres.");          
            mostrarMSSG(evt.getComponent());
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField5.getText());
        if (cad.length()!=0){
            if ((v.isInt(cad)) && (cad.length()<=4)){
                jTextField5.setToolTipText("campo correcto.");
            }
            else{
                jTextField5.requestFocus();
                jTextField5.selectAll();
                if (cad.length()>4) {
                    jTextField5.setToolTipText("longitud maxima del campo 4 caracteres.");
                }
                else{
                    jTextField5.setToolTipText("debe ingresar un NÚMERO ej: 10");
                }                       
                mostrarMSSG(evt.getComponent());
            }
        }
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusLost
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField6.getText());
        String cad2 = v.limpiarEspacios(jTextField5.getText());
        if ((!muestraValor (cad))&& (v.isInt(cad2))){
            jTextField6.requestFocus();
            jTextField6.selectAll();                                      
        }
    }//GEN-LAST:event_jTextField6FocusLost

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        // TODO add your handling code here:
        Validaciones v = new Validaciones();
        String cad = v.limpiarEspacios(jTextField6.getText());
        
        if (!"".equals(cad)) {
            if (!muestraValor (cad)){
                rc.asignarLista(jTextField6, items);
                rc.mostrarLista(jTextField6);           
            }
        }        
    }//GEN-LAST:event_jTextField6FocusGained
    
private boolean muestraValor (String cod){
    boolean existe = false;
    r_con = new Conexion();
    r_con.Connection();
    ResultSet rs = r_con.Consultar("SELECT * FROM Tasas_IVA WHERE tasa_clave = '"+cod+"'");
    try {
             while (rs.next())
            {
                jLabel8.setText(rs.getString(2));
                existe = true;
            } 
    } catch (SQLException ex) {
            
            Logger.getLogger(GUI_A_Articulo.class.getName()).log(Level.SEVERE, null, ex);
    }
    r_con.cierraConexion();
    return existe;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

public void setTitleLabel (String t){
        this.jLabel1.setText(t);
}

public void buttonBuscar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png")));
    jButton2.setText("Buscar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonAceptar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png")));
    jButton2.setText("Aceptar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    
}

public void buttonEliminar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png")));
    jButton2.setText("Eliminar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonModificar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar.png")));
    jButton2.setText("Modificar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonNuevaConsulta (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png")));
    jButton2.setText("Nueva Consulta");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    
}

public void form_onlySearch (){
    this.jTextField2.setEnabled(false);
    this.jTextField3.setEnabled(false);
    this.jTextField4.setEnabled(false);
    this.jTextField5.setEnabled(false);
    this.jTextField6.setEnabled(false);
}

public void form_Complete (){
    this.jTextField2.setEnabled(true);
    this.jTextField3.setEnabled(true);
    this.jTextField4.setEnabled(true);
    this.jTextField5.setEnabled(true);
    this.jTextField6.setEnabled(true);
}

public void limpiarForm(){
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jLabel8.setText("-");
}

}
