/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Clases_Auxiliares.ComponentListHelp;
import Clases_Auxiliares.Conexion;
import java.awt.Component;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Manolo
 */
public class GUI_A_IVA extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_A_Prod
     */
    private ComponentListHelp rc = new ComponentListHelp();
    private Conexion r_con = new Conexion();
    private ArrayList<String> items = new ArrayList<String>();
    
    public GUI_A_IVA() {
        initComponents();
        r_con.Connection();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setIconifiable(true);
        setTitle("Tasas de IVA");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/articulo.png"))); // NOI18N
        setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tasas de IVA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Código:");

        jTextField1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Sigla:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jButton2)))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        r_con.cierraConexion();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean camposNecesarios () {
       if ((jTextField1.getText().length()==0) || 
          (jTextField2.getText().length()==0) || 
          (jTextField3.getText().length()==0)) 
       {
            JOptionPane.showMessageDialog(null, "Complete todos los campos!","Atención",JOptionPane.WARNING_MESSAGE);
            return false;
       }
       return true;      
               
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        if (("Aceptar".equals(this.jButton2.getText())) && (camposNecesarios())){
            r_con = new Conexion();
            r_con.Connection();
             
            String sql = "INSERT INTO Tasas_IVA "
                        + "VALUES('"+jTextField1.getText()+"','"
                                    +jTextField2.getText()+"','"
                                    +jTextField3.getText()+"')";
            if (r_con.Insertar(sql)){
                limpiarForm();
            }
            r_con.cierraConexion();
            
        }
        else{
            if (("Buscar".equals(this.jButton2.getText()))){
                
                boolean existe = false;
                r_con = new Conexion();
                r_con.Connection();
                ResultSet rs = r_con.Consultar("SELECT * FROM Tasas_IVA WHERE tasa_clave = '"+jTextField1.getText()+"'");
                try {
                     
                     while (rs.next())
                    {     
                        if ("Baja Tasa de IVA:".equals(jLabel1.getText())){
                            jTextField1.setEnabled(false);
                        }
                        if ("Modificación Artículo:".equals(jLabel1.getText())){
                            this.form_Complete();
                        }
                        if ("Consulta Artículo:".equals(jLabel1.getText())){
                            this.form_Complete();
                        }
                        
                        jTextField2.setText(rs.getString(2));
                        jTextField3.setText(rs.getString(3));                        
                        existe = true;
                    } 
                } catch (SQLException ex) {

                    Logger.getLogger(GUI_A_IVA.class.getName()).log(Level.SEVERE, null, ex);
                }
                r_con.cierraConexion();
                if (!existe){
                    jTextField1.setEnabled(true);
                    jTextField1.requestFocus();
                    jTextField1.selectAll();
                    JOptionPane.showMessageDialog(null, "El Articulo "+jTextField1.getText()+" no se encuentra registrado.","Cuidado",JOptionPane.WARNING_MESSAGE);
                }
                else{
                    if ("Baja Tasa de IVA:".equals(jLabel1.getText())){
                        buttonEliminar ();
                     }
                     if ("Modificación Artículo:".equals(jLabel1.getText())){
                        buttonModificar ();
                     }
                     if ("Consulta Artículo:".equals(jLabel1.getText())){
                         buttonNuevaConsulta();
                     }
                     
                }
            }
            else{
                if (("Eliminar".equals(this.jButton2.getText()))){               
                r_con = new Conexion();
                r_con.Connection();
                r_con.Borrar("DELETE FROM Tasas_IVA WHERE tasa_clave = '"+jTextField1.getText()+"'");
                r_con.cierraConexion();               
                this.dispose();
                }
                
            }
          
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mostrarMSSG (Component c){
        KeyEvent ke = new KeyEvent(c, KeyEvent.KEY_PRESSED,
        System.currentTimeMillis(), InputEvent.CTRL_MASK, KeyEvent.VK_F1, KeyEvent.CHAR_UNDEFINED);
        c.dispatchEvent(ke);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

public void setTitleLabel (String t){
        this.jLabel1.setText(t);
}

public void buttonBuscar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png")));
    jButton2.setText("Buscar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonAceptar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png")));
    jButton2.setText("Aceptar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    
}

public void buttonEliminar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png")));
    jButton2.setText("Eliminar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonModificar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar.png")));
    jButton2.setText("Modificar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonNuevaConsulta (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png")));
    jButton2.setText("Nueva Consulta");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    
}

public void form_onlySearch (){
    this.jTextField2.setEnabled(false);
    this.jTextField3.setEnabled(false);
}

public void form_Complete (){
    this.jTextField2.setEnabled(true);
    this.jTextField3.setEnabled(true);
}

public void limpiarForm(){
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
}

}
