/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Facturacion;

import Contabilidad.*;
import Interface.*;
import Clases_Auxiliares.Conexion;
import Clases_Auxiliares.Fechas;
import Clases_Auxiliares.Validaciones;
import Objetos.Asiento;
import Objetos.Cliente;
import Objetos.Cuenta;
import Objetos.Usuario;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manolo
 */
public class IGUI_Facturar extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_A_Prod
     */
    private Conexion r_con;
    private String name_tabla="borrador_asientos";
    private Usuario usuario;
    
    private int renglon;
    private DefaultTableModelAsientos modelo;
    private String fechaInicio,fechaCierre,fechaDiario;    
    private boolean esCarga=false;
    
    //libreria de manejo de fechas
    private Fechas fecha = new Fechas ();    
    private Cliente cliente_factura;
    
    public IGUI_Facturar(Usuario usr,Conexion con) {
        initComponents();
        r_con=con;
        usuario=usr;
        renglon=0;

        r_con.Connection();
        inicializarTabla();
        
        this.habilitarPanel1(false);
        this.habilitarPanel2(false);     
        
        jButton1.setText("Cancelar");
 
        jButton2.setEnabled(false);
        boton7.setEnabled(false);
        jTable1.setEnabled(false);
        
        ordenarFoco();
        field_tipo_comprobante.requestFocus();
    }

    private void cargarFechas(){
        fechaInicio="";
        fechaCierre="";
        fechaDiario="";
        r_con.Connection();
        ResultSet rs=r_con.Consultar("select * from parametros_contables");
        try {
            if(rs.next()){
               fechaInicio=fecha.parseFecha(rs.getDate(1));
               fechaCierre=fecha.parseFecha(rs.getDate(2));
               fechaDiario=fecha.parseFecha(rs.getDate(4));
               
            }

            r_con.cierraConexion();    
        }        
        catch(Exception e){r_con.cierraConexion();}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        panel_datos_factura = new javax.swing.JPanel();
        field_tipo_comprobante = new javax.swing.JTextField();
        field_punto_venta = new javax.swing.JTextField();
        field_nro_cliente = new javax.swing.JTextField();
        fecha_factura = new javax.swing.JFormattedTextField();
        field_nombre = new javax.swing.JTextField();
        field_cuil_1 = new javax.swing.JTextField();
        field_cuil_2 = new javax.swing.JTextField();
        field_cuil_3 = new javax.swing.JTextField();
        field_direccion_calle = new javax.swing.JTextField();
        field_direccion_nro = new javax.swing.JTextField();
        field_localidad = new javax.swing.JTextField();
        field_situacion_IVA = new javax.swing.JTextField();
        btn_confirmar_encabezado = new javax.swing.JButton();
        label_tipo_comprobante = new javax.swing.JLabel();
        label_numero_factura = new javax.swing.JLabel();
        label_situacion = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label_mensaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion de Facturacion");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/articulo.png"))); // NOI18N
        setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Facturación:");

        panel_datos_factura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_datos_factura.setFocusCycleRoot(true);

        field_tipo_comprobante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_tipo_comprobanteFocusLost(evt);
            }
        });
        field_tipo_comprobante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_tipo_comprobanteKeyPressed(evt);
            }
        });

        field_punto_venta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_punto_ventaFocusLost(evt);
            }
        });
        field_punto_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                field_punto_ventaKeyPressed(evt);
            }
        });

        field_nro_cliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                field_nro_clienteFocusLost(evt);
            }
        });

        try {
            fecha_factura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fecha_factura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fecha_facturaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fecha_facturaFocusLost(evt);
            }
        });

        field_nombre.setEditable(false);

        field_cuil_1.setEditable(false);

        field_cuil_2.setEditable(false);

        field_cuil_3.setEditable(false);

        field_direccion_calle.setEditable(false);

        field_direccion_nro.setEditable(false);

        field_localidad.setEditable(false);

        field_situacion_IVA.setEditable(false);

        btn_confirmar_encabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        btn_confirmar_encabezado.setText("Confirmar");
        btn_confirmar_encabezado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmar_encabezadoActionPerformed(evt);
            }
        });

        label_tipo_comprobante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_tipo_comprobante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label_tipo_comprobante.setText("TIPO COMPROBANTE:");

        label_numero_factura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_numero_factura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label_numero_factura.setText(" ");

        label_situacion.setForeground(new java.awt.Color(0, 153, 51));
        label_situacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_situacion.setText("  ");

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Tipo Comprobante:");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Pto. Venta:");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Nro. Cliente:");

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Sr./Sra.:");

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("CUIL:");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("-");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("-");

        jLabel16.setText("Fecha Operación");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Direccion");

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Localidad:");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Sit. IVA");

        javax.swing.GroupLayout panel_datos_facturaLayout = new javax.swing.GroupLayout(panel_datos_factura);
        panel_datos_factura.setLayout(panel_datos_facturaLayout);
        panel_datos_facturaLayout.setHorizontalGroup(
            panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                .addComponent(label_tipo_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_numero_factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(field_tipo_comprobante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(field_punto_venta)))
                    .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                        .addComponent(fecha_factura, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                .addComponent(field_direccion_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_direccion_nro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field_localidad)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(field_situacion_IVA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_situacion, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_nro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                .addComponent(field_cuil_1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_cuil_2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(field_cuil_3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btn_confirmar_encabezado)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_datos_facturaLayout.setVerticalGroup(
            panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos_facturaLayout.createSequentialGroup()
                .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo_comprobante)
                    .addComponent(label_numero_factura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                    .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel27))
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos_facturaLayout.createSequentialGroup()
                                    .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24)
                                        .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(field_nro_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(field_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(field_cuil_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel29)
                                                .addComponent(field_cuil_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel30)
                                                .addComponent(field_cuil_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn_confirmar_encabezado)
                                                .addComponent(field_punto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(field_tipo_comprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(33, 33, 33)))
                        .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)
                            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel32)
                            .addGroup(panel_datos_facturaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(field_direccion_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(field_direccion_nro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_datos_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(field_situacion_IVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_situacion))
                                    .addComponent(field_localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setFocusCycleRoot(true);

        jLabel6.setText("Leyenda");

        jLabel12.setText("Debe");

        jLabel13.setText("Haber");

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextField8.setNextFocusableComponent(jButton4);
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton4.setText("Confirmar");
        jButton4.setNextFocusableComponent(boton7);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        boton7.setText("Borrar");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField6)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Saldo:");

        jLabel14.setText("Debe:");

        jLabel15.setText("Haber:");

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        label_mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_mensaje.setForeground(new java.awt.Color(255, 0, 0));
        label_mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mensaje.setText("  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_datos_factura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(label_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_datos_factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(label_mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jButton1.getText().equals("Cancelar")){
            int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){

                r_con.Connection();
                r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+""+" and ba_ok_carga=0");            
                this.dispose();
                r_con.cierraConexion();
            }        
        }
        else{
            this.dispose();
            r_con.cierraConexion();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        boton7.setEnabled(false);
        int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){
                //int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=1;
                modelo.removeRow(numRenglon-1);
                r_con.Connection();
                //r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+numAsiento);
                renombrarTabla();
            }        
            jButton4.setText("Confirmar");
    }                                        

    private void renombrarTabla(){
        for(int i=0;i<modelo.getRowCount();i++){
            int nuevoRen=i+1;
            modelo.setValueAt(nuevoRen+"", i, 0);
            //int num_asiento=Integer.parseInt(jTextField1.getText());
            //int num_cuenta=Integer.parseInt(jTextField3.getText());
            //renglon+"",num_cuenta+"",fecha_operacion,fecha_vencimiento,comprobante,leyenda,debe+"",haber+""
            float d=Float.parseFloat((String)modelo.getValueAt(i, 6));
            float h=Float.parseFloat((String)modelo.getValueAt(i, 7));
//            Asiento asiento=new Asiento(num_asiento,nuevoRen,campoFecha.getText(),(String)modelo.getValueAt(i, 2),(String)modelo.getValueAt(i, 3),getTipo(),num_cuenta,(String)modelo.getValueAt(i, 4),(String)modelo.getValueAt(i, 5),d,h,false,false);
//            asiento.insertar(r_con);
        }        
        this.actualizarSaldoDebeHaber();
        
    }
    
    public void borrarCampos(){

        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true);        
    }
    
    private void borrarCamposAstoBasicos(){

        jTextField7.setText("");
        jTextField8.setText("");
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true); 
    }
    
    
    private void btn_confirmar_encabezadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmar_encabezadoActionPerformed
        // TODO add your handling code here:        
        if(esCarga){
            jButton2.setEnabled(true);
            //jButton5.setText("Abandonar Asiento");
            Asiento asiento=new Asiento();
            //asiento.setOkCarga(r_con, Integer.parseInt(jTextField1.getText()),0);
        }

        habilitarPanel1(false);
        habilitarPanel2(true);
       
        jTable1.setEnabled(true);
    }//GEN-LAST:event_btn_confirmar_encabezadoActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:    

            if(!jTextField7.getText().equals("")){
                Validaciones v = new Validaciones();
                if (v.isFloat(jTextField7.getText())){
                    if (Float.parseFloat(jTextField7.getText())>=0){
                        mensajeError(" ");
                        jTextField8.setText("");
                        jTextField8.setEnabled(false);
                        jTextField8.nextFocus();
                    }
                    else{
                        mensajeError("El saldo al Debe es negativo.");
                        jTextField7.requestFocus();
                        jTextField7.selectAll();
                    }
                }
                else{
                    mensajeError("El saldo al Debe no es un valor numérico.");
                    jTextField7.requestFocus();
                    jTextField7.selectAll();
                }            
            }
            else{
                mensajeError(" ");
                jTextField8.setEnabled(true); 
                jTextField8.requestFocus();
            }
        
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:

            if(!jTextField8.getText().equals("")){
                Validaciones v = new Validaciones();
                if (v.isFloat(jTextField8.getText())){
                    if (Float.parseFloat(jTextField8.getText())>=0){
                        mensajeError(" "); 
                        jTextField7.setText("");
                        jTextField7.setEnabled(false);
                        jTextField8.nextFocus();
                    }
                    else{
                        mensajeError("El saldo al Haber es negativo.");
                        jTextField8.requestFocus();
                        jTextField8.selectAll();
                    }
                }
                else{
                    mensajeError("El saldo al Haber no es un valor numérico.");
                    jTextField8.requestFocus();
                    jTextField8.selectAll();
                }            
            }
            else{
                mensajeError(" "); 
                jTextField7.setEnabled(true);
                jTextField7.requestFocus();
            }
            
    }//GEN-LAST:event_jTextField8FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float saldo=Float.parseFloat(jTextField10.getText());
        if(saldo==0){                    
            for(int i=0;i<modelo.getRowCount();i++){
                r_con.Connection();
                //int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=Integer.parseInt(modelo.getValueAt(i, 0).toString());               
                //String cadena="update borrador_asientos set ba_ok_carga=1 where ba_nro_asiento="+numAsiento+" and ba_nro_renglon="+numRenglon;                
                this.habilitarPanel1(false);
                this.habilitarPanel2(false);
                //r_con.ActualizarSinCartel(cadena);                               
            }
            if (modelo.getRowCount()>0){
                JOptionPane.showMessageDialog(null,"El asiento fue cargado correctamente");    
            }
            else{
                JOptionPane.showMessageDialog(null,"Realice una nueva Carga"); 
            }            
            this.habilitarPanel2(false);
            //jButton6.setEnabled(true);
            //jButton5.setEnabled(true);
            boton7.setEnabled(false);
            jButton1.setText("Cancelar");
            this.inicializarTabla();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"El asiento que usted intenta registrar no balancea");
        }
        jTextField9.setText(0+"");
        jTextField10.setText(0+"");
        jTextField11.setText(0+"");
        r_con.cierraConexion();
    }//GEN-LAST:event_jButton2ActionPerformed


    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:        
        if(jTable1.isEnabled()){
            if(evt.getClickCount()==2){            
                int fila=jTable1.getSelectedRow();
            //"Renglon","Nro. Cuenta","Fecha Oper.","Fecha Vto.","Nro Comprobante","Leyenda","Debe","Haber"
                int numRenglon=Integer.parseInt((String)modelo.getValueAt(fila, 0));
                int numCuenta=Integer.parseInt((String)modelo.getValueAt(fila, 1));
                String fechaOp=(String)modelo.getValueAt(fila, 2);
                String fechaVto=(String)modelo.getValueAt(fila, 3);
                String comprobante=(String)modelo.getValueAt(fila, 4);
                String leyenda=(String)modelo.getValueAt(fila, 5);
                BigDecimal debe=convertirEnBigDecimal((String)modelo.getValueAt(fila, 6));
                BigDecimal haber=convertirEnBigDecimal((String)modelo.getValueAt(fila, 7));

                jTextField6.setText(leyenda);
                jTextField7.setText("");
                jTextField8.setText("");
                if(debe.floatValue()==0)
                    jTextField8.setText(haber+"");
                else
                    jTextField7.setText(debe+"");
                habilitarPanel2(true);
                boton7.setEnabled(true);
                jButton4.setText("Modificar");
            }               
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!jTextField7.isEnabled()){
            jTextField7.setText("");
        }
        if(!jTextField8.isEnabled()){
            jTextField8.setText("");
        }        
        if(jButton4.getText().equals("Confirmar")){
            if(controlarCampos()){
                jButton2.setEnabled(true);
                jButton1.setText("Abandonar Asiento");
                cargarTabla();
                borrarCamposAstoBasicos();
                mensajeError(" ");
            }
            else
            {
                mensajeError("Debe completar todos los campos");
            }
        }
        else
        {
            if(controlarCampos()){
                jButton4.setText("Confirmar");
                actualizarTabla();
                mensajeError(" ");
                borrarCamposAstoBasicos();                
            }
            else
                mensajeError("Debe completar todos los campos");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        boton7.setEnabled(false);
        int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){
                //int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=1;
                modelo.removeRow(numRenglon-1);
                r_con.Connection();
                //r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+numAsiento);
                renombrarTabla();
            }
            else
                boton7.setEnabled(true);
            jButton4.setText("Confirmar");
    }//GEN-LAST:event_boton7ActionPerformed

    private void field_tipo_comprobanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_tipo_comprobanteFocusLost
        boolean es_componente=false;
        //voy a preguntar si la componente que me saco el foco es algun campo del panel de datos de asientos
        int i=0;        
        Component[] components = panel_datos_factura.getComponents();
        while ((!es_componente)&&(i<components.length)){
            if (components[i]==evt.getOppositeComponent()){
                es_componente=true;
            }
            i++;
        }
        
        if((es_componente)&&(field_tipo_comprobante.isEditable())){        
            if (!field_tipo_comprobante.getText().equals("")){
                String detalle = get_TipoComprobante(field_tipo_comprobante.getText());
                if (!detalle.equals("")){
                    label_tipo_comprobante.setText(detalle+" Nº: ");
                    mensajeError(" ");
                }
                else{
                    field_tipo_comprobante.requestFocus();
                    label_tipo_comprobante.setText("TIPO COMPROBANTE:");
                    generarAyuda_Tipo_Comprobante();
                }
            }
            else{
                label_tipo_comprobante.setText("TIPO COMPROBANTE:");
                mensajeError("Por favor, seleccione un tipo de comprobante");
            }
        }
        
    }//GEN-LAST:event_field_tipo_comprobanteFocusLost
    
    private void field_punto_ventaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_punto_ventaFocusLost
        // TODO add your handling code here:
        boolean es_componente=false;
        //voy a preguntar si la componente que me saco el foco es algun campo del panel de datos de asientos
        int i=0;        
        Component[] components = panel_datos_factura.getComponents();
        while ((!es_componente)&&(i<components.length)){
            if (components[i]==evt.getOppositeComponent()){
                es_componente=true;
            }
            i++;
        }
        
        if((es_componente)&&(!field_punto_venta.getText().equals(""))){
            if (isPuntoVenta(field_punto_venta.getText())){
                String detalle = get_NumeroComprobante(field_punto_venta.getText(),field_tipo_comprobante.getText());
                if (!detalle.equals("")){
                    String numero_com="00";
                    String numero_pto="0000";
                    if ((!field_tipo_comprobante.getText().equals(""))&&(!field_punto_venta.getText().equals(""))){
                        numero_com = String.format("%02d", Integer.parseInt(field_tipo_comprobante.getText()));
                        numero_pto = String.format("%04d", Integer.parseInt(field_punto_venta.getText()));
                    }                
                    String numero_fac = String.format("%08d", Integer.parseInt(detalle));
                    label_numero_factura.setText(numero_com+"-"+numero_pto+"-"+numero_fac);
                    mensajeError(" ");
                }
                else{
                    label_numero_factura.setText(" ");
                    field_tipo_comprobante.requestFocus();
                    mensajeError("El tipo de comprobante "+field_tipo_comprobante.getText()+" no esta disponible para el punto de venta "+field_punto_venta.getText());
                }
            }
            else {
                field_punto_venta.requestFocus();
                generarAyuda_Punto_Venta();   
            }
        }
        else{
            label_numero_factura.setText(" ");
            mensajeError("Por favor, seleccione un punto de venta");
        }
    }//GEN-LAST:event_field_punto_ventaFocusLost

    private void field_tipo_comprobanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_tipo_comprobanteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1){            
            generarAyuda_Tipo_Comprobante();
        }
    }//GEN-LAST:event_field_tipo_comprobanteKeyPressed

    private void field_punto_ventaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_punto_ventaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_F1){            
            generarAyuda_Punto_Venta();
        }
    }//GEN-LAST:event_field_punto_ventaKeyPressed

    private void fecha_facturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fecha_facturaFocusGained
        // TODO add your handling code here:
        fecha_factura.select(0,0);
    }//GEN-LAST:event_fecha_facturaFocusGained

    private void fecha_facturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fecha_facturaFocusLost
        // TODO add your handling code here:
        if (!fecha.isFechaValida(fecha_factura.getText())){
            fecha_factura.requestFocus();    
            mensajeError("La Fecha ingresada no se reconoce como valida.");    
        }
        else{
            mensajeError(" ");
        }
    }//GEN-LAST:event_fecha_facturaFocusLost

    private void field_nro_clienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_field_nro_clienteFocusLost
        // TODO add your handling code here:
        boolean es_componente=false;
        //voy a preguntar si la componente que me saco el foco es algun campo del panel de datos de asientos
        int i=0;        
        Component[] components = panel_datos_factura.getComponents();
        while ((!es_componente)&&(i<components.length)){
            if (components[i]==evt.getOppositeComponent()){
                es_componente=true;
            }
            i++;
        }
        
        if((es_componente)&&(!field_nro_cliente.getText().equals(""))){
            Cliente cli = get_Cliente (field_nro_cliente.getText());
            if (cli.getCodigo_cliente()!=0){
                cliente_factura = cli;
                field_nombre.setText(cli.getNombre_cliente()+" "+cli.getApellido_cliente());
                field_cuil_1.setText(cli.getCuil_prefijo_cliente());
                field_cuil_2.setText(cli.getCuil_dni_cliente());
                field_cuil_3.setText(cli.getCuil_digito_cliente());
                field_direccion_calle.setText(cli.getCalle_cliente());
                field_direccion_nro.setText(cli.getNumero_calle_cliente());
                field_localidad.setText(cli.getLocalidad_cliente());
                field_situacion_IVA.setText(""+cli.getCodigo_situacion_IVA_cliente());
                label_situacion.setText(cli.getDescripcion_situacion_IVA_cliente());               
                mensajeError(" ");
            }
            else{
                label_situacion.setText(" ");
                field_nro_cliente.requestFocus();
                //generarAyuda_Punto_Venta();      
            }
        }
        else{
            label_situacion.setText(" ");
            mensajeError("Por favor, ingrese un cliente");
        }
        get_Cliente(field_nro_cliente.getText());
    }//GEN-LAST:event_field_nro_clienteFocusLost
    
    private String get_TipoComprobante (String codigo){
        String detalle = "";
        try {            
            r_con.Connection();
            String sql = ( "SELECT * "+
                    " FROM tipo_comprobante"+
                    " WHERE tc_codigo = "+codigo);
            
            ResultSet res = r_con.Consultar(sql);
            while(res.next()){
                detalle = res.getString(2);
            }
            res.close();           
        } catch (SQLException ex) {
            Logger.getLogger(IGUI_Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
                    r_con.cierraConexion();
                  }
        return detalle;
    }
    
    private String get_NumeroComprobante (String pto, String codigo){
        String detalle = "";
        try {            
            r_con.Connection();
            String sql = ( "SELECT * "+
                    " FROM ptoventa_x_tipocomprobante"+
                    " WHERE vxc_id_pto_venta = "+pto+" AND vxc_id_tipo_comprobante = "+codigo);
            
            ResultSet res = r_con.Consultar(sql);
            while(res.next()){
                detalle = res.getString(3);
            }
            res.close();           
        } catch (SQLException ex) {
            Logger.getLogger(IGUI_Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
                    r_con.cierraConexion();
                  }
        return detalle;
    }
    
    private boolean isPuntoVenta (String codigo){
        boolean existe = false;
        try {
            r_con.Connection();
            String sql = (
                        "SELECT * "+
                        " FROM punto_venta"+
                        " WHERE pv_codigo = "+codigo);           
            
            ResultSet res = r_con.Consultar(sql);
            
            while(res.next()){
                existe = true;
            }
            res.close();
        } catch (SQLException ex) {
            Logger.getLogger(IGUI_Productos.class.getName()).log(Level.SEVERE, null, ex);
        } finally {            
            r_con.cierraConexion();
        }
        return existe;
    }
    
    private Cliente get_Cliente (String codigo){
        String detalle = "";
        Cliente cli = new Cliente();
        try {            
            r_con.Connection();
            String sql = ( "SELECT cli_codigo, cli_nombre, cli_apellido, cli_fecha_nac, cli_cuit, loc_descripcion, cli_direccion, cli_calle, cli_sit_frente_iva, sfi_descripcion " +
                           "FROM clientes, localidades, situacion_frente_iva " +
                           "WHERE (cli_codigo = "+codigo+") AND (cli_localidad = loc_id) AND (cli_sit_frente_iva = sfi_id)");
            
            ResultSet res = r_con.Consultar(sql);           
            
            while(res.next()){
                cli.setCodigo_cliente(Integer.parseInt(res.getString(1)));
                cli.setNombre_cliente(res.getString(2));
                cli.setApellido_cliente(res.getString(3));
                String fec_nac = fecha.convertirBarras(res.getString(4));                
                cli.setFecha_nacimiento_cliente(fec_nac);
                String cuil = res.getString(5);
                cli.setCuil_prefijo_cliente(cuil.substring(0,2));
                cli.setCuil_dni_cliente(cuil.substring(2,cuil.length()-1));
                cli.setCuil_digito_cliente(cuil.substring(cuil.length()-1,cuil.length()));
                cli.setLocalidad_cliente(res.getString(6));
                cli.setCalle_cliente(res.getString(7));
                cli.setNumero_calle_cliente(res.getString(8));
                cli.setCodigo_situacion_IVA_cliente(Integer.parseInt(res.getString(9)));
                cli.setDescripcion_situacion_IVA_cliente(res.getString(10));
            }
            res.close();           
        } catch (SQLException ex) {
            Logger.getLogger(IGUI_Facturar.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
                    r_con.cierraConexion();
                  }
        //System.out.println(cli.toString());
        return cli;
    }
    
    public void generarAyuda_Tipo_Comprobante(){
        GUI_Ayuda_Tipo_Comprobante np = new GUI_Ayuda_Tipo_Comprobante(r_con,this);
        //lo centro respecto a x
        int x = (this.getDesktopPane().getWidth() / 2) - np.getWidth() / 2;
        int y = (this.getDesktopPane().getHeight() / 2) - np.getHeight() / 2;
        np.setLocation(x, y);        
        //lo hago visible, lo agrego al DesktopPanel, hago foco.
        np.setVisible(true);
        this.getDesktopPane().add(np);
        try {                
            np.setSelected(true);            
         } 
        catch (PropertyVetoException ex) {
            Logger.getLogger(IGUI_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        np.moveToFront();
        np.requestFocus();         
    }
    
     public void generarAyuda_Punto_Venta(){
        GUI_Ayuda_Punto_Venta np = new GUI_Ayuda_Punto_Venta(r_con,this);
        //lo centro respecto a x
        int x = (this.getDesktopPane().getWidth() / 2) - np.getWidth() / 2;
        int y = (this.getDesktopPane().getHeight() / 2) - np.getHeight() / 2;
        np.setLocation(x, y);        
        //lo hago visible, lo agrego al DesktopPanel, hago foco.
        np.setVisible(true);
        this.getDesktopPane().add(np);
        try {                
            np.setSelected(true);            
         } 
        catch (PropertyVetoException ex) {
            Logger.getLogger(IGUI_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        np.moveToFront();
        np.requestFocus();         
    }
    
    private void actualizarTabla(){
        int numRenglon=(1-1);
            
            int ren=numRenglon+1;
            modelo.setValueAt(ren+"",numRenglon , 0);
            modelo.setValueAt(1,numRenglon , 1);
            modelo.setValueAt(1,numRenglon , 2);
            modelo.setValueAt(1,numRenglon , 3);
            modelo.setValueAt(jTextField6.getText(),numRenglon , 5);
            BigDecimal d=new BigDecimal(0);
            BigDecimal h=new BigDecimal(0);
            if(jTextField7.isEnabled()){
                d=convertirEnBigDecimal(Float.parseFloat(jTextField7.getText())+"");
            }
            else
            {
                h=convertirEnBigDecimal(Float.parseFloat(jTextField8.getText())+"");
            }    
            modelo.setValueAt(d+"",numRenglon , 6);
            modelo.setValueAt(h+"",numRenglon , 7);
            //int numAsiento=Integer.parseInt(jTextField1.getText());
            r_con.Connection();

            this.actualizarSaldoDebeHaber();
    }
    
    
    private void deshabilitarCampos(){
        this.inicializarTabla();
                 
//        jButton3.setEnabled(false);

        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }
    
    private void cargarCampos(int numAsiento){
        try {
            r_con.Connection();
            ResultSet rs=r_con.Consultar("select * from borrador_asientos where ba_nro_asiento="+numAsiento);
            Asiento asiento=null;
            renglon=0;
            BigDecimal debeTotal=new BigDecimal(0);
            BigDecimal haberTotal=new BigDecimal(0);
            while(rs.next()){
                renglon++;
                    asiento=new Asiento(rs.getInt(1),rs.getInt(2),rs.getDate(3).toString(),
                                            rs.getDate(6).toString(),rs.getDate(7).toString(),
                                            rs.getString(4),rs.getInt(5),rs.getString(8),
                                            rs.getString(9),rs.getFloat(10),rs.getFloat(11),
                                            rs.getBoolean(12),rs.getBoolean(13));
                modelo.addRow(asiento.getRenglonModelo());
                jTable1.setModel(modelo);           
                BigDecimal asDebe=convertirEnBigDecimal(asiento.getDebe()+"");
                debeTotal=sumarBigDecimal(debeTotal+"",asDebe+"");
                BigDecimal asHaber=convertirEnBigDecimal(asiento.getHaber()+"");
                haberTotal=sumarBigDecimal(haberTotal+"",asHaber+"");
            }
            jTextField9.setText(debeTotal+"");
            jTextField11.setText(haberTotal+"");
            BigDecimal saldo=sumarBigDecimal(debeTotal+"","-"+haberTotal);
            jTextField10.setText(saldo+"");
            if(asiento!=null){                                                             
                //campoFecha.setText(fecha.convertirBarras(asiento.getFecha_contable()));                
                
                if(asiento.getTipo().equals("Asiento Apertura")){
                    //jRadioButton1.setSelected(true);
                }
                else{
                    if(asiento.getTipo().equals("Asiento Normal")){
                        //jRadioButton2.setSelected(true);
                    }
                    else{
                        //jRadioButton3.setSelected(true);
                    }                        
                }
            }
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        
    private void habilitarPanelCarga1(boolean valor){
        //campoFecha.setEnabled(!valor);
        //campoFecha.setEditable(!valor);
        //jTextField1.setEnabled(valor);
        //jTextField1.setEditable(valor);
        btn_confirmar_encabezado.setEnabled(valor);
        //jTextField1.requestFocus();
        //this.habilitarRadioButtons(!valor);
        
    }
    
    private void habilitarPanel1(boolean valor){
        //campoFecha.setEnabled(valor);
        //jTextField1.setEnabled(valor);
        //this.habilitarRadioButtons(valor);
        btn_confirmar_encabezado.setEnabled(valor);
    }
    
    private void habilitarPanel2(boolean valor){

        jTextField6.setEnabled(valor);
        jTextField7.setEnabled(valor);
        jTextField8.setEnabled(valor);

        boton7.setEnabled(!valor);
        jButton4.setEnabled(valor);
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton7;
    private javax.swing.JButton btn_confirmar_encabezado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField fecha_factura;
    private javax.swing.JTextField field_cuil_1;
    private javax.swing.JTextField field_cuil_2;
    private javax.swing.JTextField field_cuil_3;
    private javax.swing.JTextField field_direccion_calle;
    private javax.swing.JTextField field_direccion_nro;
    private javax.swing.JTextField field_localidad;
    private javax.swing.JTextField field_nombre;
    private javax.swing.JTextField field_nro_cliente;
    private javax.swing.JTextField field_punto_venta;
    private javax.swing.JTextField field_situacion_IVA;
    private javax.swing.JTextField field_tipo_comprobante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel label_mensaje;
    private javax.swing.JLabel label_numero_factura;
    private javax.swing.JLabel label_situacion;
    private javax.swing.JLabel label_tipo_comprobante;
    private javax.swing.JPanel panel_datos_factura;
    // End of variables declaration//GEN-END:variables


    private int getNumeroAsiento() {
        int asiento=-1;
        try {                        
            r_con.Connection();
            ResultSet rs=r_con.Consultar("select max(ba_nro_asiento) from "+name_tabla);
            rs.next();
            asiento=rs.getInt(1)+1;
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);            
        }
        return asiento;
    }

    private Cuenta obtenerCuenta(String nroCta) {
        Cuenta aux=null;
        try {            
            r_con.Connection();
            int nroCuenta=Integer.parseInt(nroCta);
            ResultSet rs=r_con.Consultar("select * from plan_cuentas where pc_nro_cuenta="+nroCuenta);
            if(rs.next()){
                aux=new Cuenta();
                aux.setCodigo_PC(rs.getString(1));
                aux.setNumero_C(rs.getInt(2));
                aux.setNombre_C(rs.getString(3));
                aux.setImputable_C(rs.getBoolean(4));
                aux.setNumero_Padre_C(rs.getInt(5));
            }
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return aux;
    }



    private void inicializarTabla() {        
        modelo=new DefaultTableModelAsientos();
        String [] columnas= {"Renglon","Nro. Cuenta","Fecha Oper.","Fecha Vto.","Nro Comprobante","Leyenda","Debe","Haber"};
        modelo.setColumnIdentifiers(columnas); 
        jTable1.setModel(modelo);        
    }

    private void mensajeError(String msj) {
        label_mensaje.setText(msj);        
    }
    
    /**
     * Nos retorna el numero del tipo, segun el radio button seleccionado
     * @return 
     */
    private String getTipo(){

        return "";
    }
    
    private void cargarTabla(){
        String leyenda=jTextField6.getText();
        BigDecimal debe,haber;        
        debe=new BigDecimal(0);
        haber=new BigDecimal(0);
        if((jTextField7.isEnabled())&&(!jTextField7.equals(""))){
            haber=new BigDecimal(0);
            float d=Float.parseFloat(jTextField7.getText());
            debe=convertirEnBigDecimal(d+"");
        }
        else
        {
            if((jTextField8.isEnabled())&&(!jTextField8.equals(""))){
                debe=new BigDecimal(0);
                float h=Float.parseFloat(jTextField8.getText());
                haber=convertirEnBigDecimal(h+"");
            }
        }        
        BigDecimal debeTotal=convertirEnBigDecimal(jTextField9.getText());
        debeTotal=sumarBigDecimal(debeTotal+"",debe+"");
        BigDecimal haberTotal=convertirEnBigDecimal(jTextField11.getText());        
        haberTotal=sumarBigDecimal(haberTotal+"",haber+"");
        BigDecimal saldo=sumarBigDecimal(haberTotal+"","-"+debeTotal);
        jTextField9.setText(debeTotal+"");
        jTextField11.setText(haberTotal+"");
        jTextField10.setText(saldo+"");
        
        //Asiento asiento=new Asiento(num_asiento,renglon,fecha_contabilidad,fecha_operacion,fecha_vencimiento,tipo,num_cuenta,comprobante,leyenda,debe.floatValue(),haber.floatValue(),false,false);
        //asiento.insertar(r_con);
        
        String []aux_modelo={renglon+"",leyenda,debe+"",haber+""};
        modelo.addRow(aux_modelo);  
        jTable1.setModel(modelo);
        renglon++;
    }
    
    /**
     * Nos controla los campos de Leyenda y Comprobante
     * @return true en caso de que ambos esten completos false de lo contrario
     */
    private boolean controlarCampos(){
        if((!jTextField6.getText().equals("")))
            return true;
        else
            return false;
    }
    
    /**
     * Recorre la tabla y recalcula el debe el haber y saldo 
     */
    public void actualizarSaldoDebeHaber(){
        BigDecimal debe=new BigDecimal(0);
        BigDecimal haber=new BigDecimal(0);
        String dAux;
        String hAux;
        for(int i=0;i<modelo.getRowCount();i++){
            dAux=modelo.getValueAt(i, 6)+"";
            hAux=modelo.getValueAt(i, 7)+"";
            debe=sumarBigDecimal(debe+"",dAux);
            haber=sumarBigDecimal(haber+"",hAux);
        }
        jTextField9.setText(debe+"");        
        jTextField11.setText(haber+"");
        jTextField10.setText(sumarBigDecimal(debe+"","-"+haber)+"");
    }
    
    private BigDecimal sumarBigDecimal(String num1,String num2){        
        float num1Float=Float.parseFloat(num1);
        float num2Float=Float.parseFloat(num2);
        String formato1=new DecimalFormat("0.00").format(num1Float);
        String formato2=new DecimalFormat("0.00").format(num2Float);
        formato1=formato1.replace(',', '.');
        formato2=formato2.replace(',', '.');        
        BigDecimal num1BigD=new BigDecimal(formato1);
        BigDecimal num2BigD=new BigDecimal(formato2);
        BigDecimal suma=num1BigD.add(num2BigD);        
        return suma;
    }
    
    private BigDecimal convertirEnBigDecimal(String num){
        float num1=Float.parseFloat(num);
        String formato=new DecimalFormat("0.00").format(num1);
        formato=formato.replace(',','.');
        BigDecimal bigNum=new BigDecimal(formato);
        return bigNum;
    }
    
     private void ordenarFoco() {        
        field_tipo_comprobante.setNextFocusableComponent(field_punto_venta);
        field_punto_venta.setNextFocusableComponent(field_nro_cliente);
        field_nro_cliente.setNextFocusableComponent(fecha_factura);
        fecha_factura.setNextFocusableComponent(btn_confirmar_encabezado);
        btn_confirmar_encabezado.setNextFocusableComponent(field_tipo_comprobante);               
    }
    
        
    
}
