/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Contabilidad;

import Interface.*;
import Clases_Auxiliares.Conexion;
import Objetos.Cuenta;
import Objetos.Usuario;
import java.awt.Component;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Enumeration;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Manolo
 */
public class GUI_Ayuda_PC extends javax.swing.JInternalFrame {
 private Vector<Cuenta> vecChildren = new Vector<Cuenta>();
    private int cant_count=0;
    private DefaultTreeModel modelo1 = null;
    private DefaultMutableTreeNode root1 = null;
    private DefaultMutableTreeNode parent1 = null;
    private DefaultMutableTreeNode childnode = null;
    
    private Conexion r_con;
    private Usuario usr;
    private String nameTable = "plan_cuentas";
    private Cuenta cuenta;
    
    private JTextField campo;
    
    private JTextField nroCuentaField,nombreCuentaField;

   
    
    public GUI_Ayuda_PC(Usuario u,Conexion con,JTextField campo1,JTextField campo2) {
        initComponents();
        r_con=con;
        usr=u;
        cuenta=null;
        r_con.Connection();
        jButton2.setEnabled(false);
        nroCuentaField=campo1;
        nombreCuentaField=campo2;
        
        //((GUI_Plan_Cuentas)o).setVisible(false);
        cargarArbol(); 
        expandirArbol ();
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTreeConta = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Plan de Cuentas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/articulo.png"))); // NOI18N
        setInheritsPopupMenu(true);

        JTreeConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeContaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTreeConta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Cta.:");

        jLabel2.setText("Número de Cta.:");

        jLabel3.setText("-");

        jLabel4.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton2)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Cuenta getCuenta() {
        return cuenta;
    }
            
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        r_con.cierraConexion();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);    
        r_con.cierraConexion();
        nroCuentaField.setText(cuenta.getNumero_C()+"");
        nombreCuentaField.setText(cuenta.getNombre_C());
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JTreeContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeContaMouseClicked
        // TODO add your handling code here:
          DefaultMutableTreeNode  node = (DefaultMutableTreeNode) JTreeConta.getLastSelectedPathComponent();

        if (node == null){
            return;
        }
        else{                                            
                Object nodeInfo = node.getUserObject();
                cuenta = (Cuenta) nodeInfo;
                jLabel4.setText(""+cuenta.getNumero_C());
                jLabel3.setText(cuenta.getNombre_C());
                
                if(cuenta.isImputable_C()){
                    jButton2.setEnabled(true);
                }
                else
                    jButton2.setEnabled(false);
        } 
            
    }//GEN-LAST:event_JTreeContaMouseClicked
    
  public void cargarArbol() {
        //inicializo el arbol
        inicializarArbol();
        
        //cargo las cuentas hijo
        r_con.Connection();
        int count = 0;
        int aux = 0;
        Enumeration e = root1.breadthFirstEnumeration();
        while (e.hasMoreElements()) {
            parent1 = (DefaultMutableTreeNode) e.nextElement();
            if (count > aux) {
                try {
                    Cuenta objChildren = (Cuenta) parent1.getUserObject();
                    ResultSet res = r_con.Consultar("select pc_codigo_plan_cuenta,pc_nro_cuenta,pc_nombre_cuenta,pc_imputable,pc_id_padre from plan_cuentas where pc_id_padre="+objChildren.getNumero_C()+" order by pc_codigo_plan_cuenta");
                    while (res.next()) {
                        Cuenta hijo = new Cuenta (res.getString(1), res.getInt(2), res.getString(3),res.getBoolean(4),res.getInt(5));
                        childnode = new DefaultMutableTreeNode(hijo);
                        modelo1.insertNodeInto(childnode, parent1, parent1.getChildCount());                        
                    }
                    res.close();
                } catch (SQLException ex) {
                    Logger.getLogger(GUI_Plan_Cuentas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            //Pregunto si llego al fin.
            if (e.hasMoreElements() == false) {
                int toEle = totalElementos(root1.breadthFirstEnumeration());
                if (cant_count < toEle) {
                    aux = count;
		    count = -1;                    
                    e = root1.breadthFirstEnumeration();
                    cant_count = toEle;
                } else {
                    break;
                }
            }
            count++;
        }
        System.out.println(cant_count);
        this.JTreeConta.setModel(modelo1);
        r_con.cierraConexion();
    }
    
   /**
     * Metodo PRIVADO de cargarArbol que inicializa el Arbol con las primeras cuentas, Activo, Pasivo, etc
     */
    private void inicializarArbol() {
        //pido el objeto -1 por que es el Plan de Cuentas
        Cuenta obj = (Cuenta) getHijos(-1).get(0);
        root1 = new DefaultMutableTreeNode(obj);
        modelo1 = new DefaultTreeModel(root1);
        Enumeration e = root1.breadthFirstEnumeration();
        parent1 = (DefaultMutableTreeNode) e.nextElement();
        Cuenta objChildren = (Cuenta) parent1.getUserObject();
        
        //consigo los hijos de idparent
        vecChildren = getHijos(objChildren.getNumero_C());

        for (int k = 0; k < vecChildren.size(); k++) {
            cant_count++;
            Cuenta hijo;
            hijo = (Cuenta) vecChildren.get(k);
            modelo1.insertNodeInto(new DefaultMutableTreeNode(hijo), parent1, parent1.getChildCount());
        }
        this.JTreeConta.setModel(modelo1);
    }

    
    
   public int totalElementos(Enumeration e) {
        int cont = 0;
        while (e.hasMoreElements()) {
            e.nextElement();
            cont++;
        }
        return cont;
    }  
  
   
    /**
     * Return un vector con los hijos.
     * Id,Idparent,Descripcion,Order
     * @param Id
     * @return
     */
    public Vector getHijos (int Id) {
        r_con.Connection();
        Vector<Cuenta> data = new Vector<Cuenta>();
        try {            
            ResultSet res = r_con.Consultar("select pc_codigo_plan_cuenta,pc_nro_cuenta,pc_nombre_cuenta,pc_imputable,pc_id_padre from "+nameTable+" where pc_id_padre="+Id+" order by pc_codigo_plan_cuenta");

            while (res.next()) {
                data.addElement(new Cuenta(res.getString(1), res.getInt(2), res.getString(3),res.getBoolean(4),res.getInt(5)));
            }
            res.close();
        } catch (SQLException e) {
            System.out.println(e);
            r_con.cierraConexion();
        }
        r_con.cierraConexion();
        return data;
    }
    
   
   
    private void mostrarMSSG (Component c){
        KeyEvent ke = new KeyEvent(c, KeyEvent.KEY_PRESSED,
        System.currentTimeMillis(), InputEvent.CTRL_MASK, KeyEvent.VK_F1, KeyEvent.CHAR_UNDEFINED);
        c.dispatchEvent(ke);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree JTreeConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

public void setTitleLabel (String t){
        this.jLabel1.setText(t);
}

public void buttonBuscar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/buscar.png")));
    jButton2.setText("Buscar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
}

public void buttonAceptar (){
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png")));
    jButton2.setText("Aceptar");
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    
}

public void expandirArbol (){
        int j=JTreeConta.getRowCount();
        int i=0;
        while( i < j) {
            JTreeConta.expandRow(i);
            i += 1;
            j = JTreeConta.getRowCount();
      }
}

public void form_onlySearch (){
    //this.jTextField2.setEnabled(false);
}

public void form_Complete (){
    //this.jTextField2.setEnabled(true);
}

public void limpiarForm(){
    
}

}
