/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Contabilidad;

import Interface.*;
import Clases_Auxiliares.Conexion;
import Clases_Auxiliares.Fechas;
import Clases_Auxiliares.Validaciones;
import Objetos.Asiento;
import Objetos.Cuenta;
import Objetos.Usuario;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manolo
 */
public class GUI_Cargar_Asiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUI_A_Prod
     */
    private Conexion r_con;
    private String nameTabla="borrador_asientos";
    private Cuenta cuenta;
    private Usuario usuario;
    private int renglon;
    private DefaultTableModelAsientos modelo;
    private String fechaInicio,fechaCierre,fechaDiario;    
    private boolean esCarga=false;
    //libreria de manejo de fechas
    private Fechas fecha = new Fechas ();
    
    public GUI_Cargar_Asiento(Usuario usr,Conexion con) {
        initComponents();
        r_con=con;
        usuario=usr;
        renglon=0;
        cargarFechas();
        r_con.Connection();
        inicializarTabla();
        
        this.habilitarPanel1(false);
        this.habilitarPanel2(false);     
        
        jButton1.setText("Cancelar");
        campoFecha.setText(fecha.getHoy());   
        jButton2.setEnabled(false);
        boton7.setEnabled(false);
        jTable1.setEnabled(false);
        jButton5.requestFocus();
    }

    private void cargarFechas(){
        fechaInicio="";
        fechaCierre="";
        fechaDiario="";
        r_con.Connection();
        ResultSet rs=r_con.Consultar("select * from parametros_contables");
        try {
            if(rs.next()){
               fechaInicio=fecha.parseFecha(rs.getDate(1));
               fechaCierre=fecha.parseFecha(rs.getDate(2));
               fechaDiario=fecha.parseFecha(rs.getDate(4));
               
            }
            jLabel20.setText(fechaInicio);           
            jLabel21.setText(fechaCierre);
            jLabel23.setText(fechaDiario);
            r_con.cierraConexion();    
        }        
        catch(Exception e){r_con.cierraConexion();}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        campoFecha1 = new javax.swing.JFormattedTextField();
        campoFecha2 = new javax.swing.JFormattedTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(0));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Asientos Contables");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/articulo.png"))); // NOI18N
        setInheritsPopupMenu(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Asientos Contables:");

        jPanel5.setFocusCycleRoot(true);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/retomar_asi.png"))); // NOI18N
        jButton6.setText("Retomar Asiento");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel18.setText("Fecha Apertura:");

        jLabel19.setText("Fecha Cierre:");

        jLabel20.setText("-");

        jLabel21.setText("-");

        jLabel22.setText("Fecha Ult. Impresion Diario:");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("-");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cargar_asi.png"))); // NOI18N
        jButton5.setText("Cargar Asiento");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton6)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.setFocusCycleRoot(true);

        jLabel3.setText("Fecha Contable:");

        jLabel4.setText("Nro. Asiento:");

        jLabel16.setText("Tipo:");

        try {
            campoFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFechaFocusLost(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Apertura");
        jRadioButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRadioButton1FocusLost(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Normal");
        jRadioButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRadioButton2FocusLost(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Cierre");
        jRadioButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jRadioButton3FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                .addComponent(jRadioButton3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel16)
                                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton3)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setFocusCycleRoot(true);

        jLabel6.setText("Leyenda");

        jLabel5.setText("Nro. Cuenta (F1)");

        jLabel7.setText("Nombre Cuenta");

        jLabel8.setText("Fecha Operación");

        jLabel9.setText("Fecha Vencimiento");

        jLabel10.setText("Nro. Comprobante");

        jLabel11.setText("Nro. Renglon");

        jLabel12.setText("Debe");

        jLabel13.setText("Haber");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("  ");

        jTextField2.setEditable(false);

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        try {
            campoFecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFecha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFecha1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFecha1FocusLost(evt);
            }
        });

        try {
            campoFecha2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoFecha2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoFecha2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFecha2FocusLost(evt);
            }
        });

        jTextField5.setNextFocusableComponent(jTextField6);
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });

        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });

        jTextField8.setNextFocusableComponent(jButton4);
        jTextField8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField8FocusLost(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton4.setText("Confirmar");
        jButton4.setNextFocusableComponent(boton7);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar.png"))); // NOI18N
        boton7.setText("Borrar");
        boton7.setNextFocusableComponent(jTextField3);
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(jTextField4)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTextField6)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField7)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(campoFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField5)
                    .addComponent(boton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Saldo:");

        jLabel14.setText("Debe:");

        jLabel15.setText("Haber:");

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar.png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel14)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jButton1.getText().equals("Cancelar")){
            int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){
                int numAsiento=Integer.parseInt(jTextField1.getText());
                r_con.Connection();
                r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+numAsiento+" and ba_ok_carga=0");            
                this.dispose();
                r_con.cierraConexion();
            }        
        }
        else{
            this.dispose();
            r_con.cierraConexion();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        boton7.setEnabled(false);
        int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){
                int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=Integer.parseInt(jTextField2.getText());
                modelo.removeRow(numRenglon-1);
                r_con.Connection();
                r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+numAsiento);
                renombrarTabla();
            }        
            jButton4.setText("Confirmar");
    }                                        

    private void renombrarTabla(){
        for(int i=0;i<modelo.getRowCount();i++){
            int nuevoRen=i+1;
            modelo.setValueAt(nuevoRen+"", i, 0);
            int num_asiento=Integer.parseInt(jTextField1.getText());
            int num_cuenta=Integer.parseInt(jTextField3.getText());
            //renglon+"",num_cuenta+"",fecha_operacion,fecha_vencimiento,comprobante,leyenda,debe+"",haber+""
            float d=Float.parseFloat((String)modelo.getValueAt(i, 6));
            float h=Float.parseFloat((String)modelo.getValueAt(i, 7));
            Asiento asiento=new Asiento(num_asiento,nuevoRen,campoFecha.getText(),(String)modelo.getValueAt(i, 2),(String)modelo.getValueAt(i, 3),getTipo(),num_cuenta,(String)modelo.getValueAt(i, 4),(String)modelo.getValueAt(i, 5),d,h,false,false);
            asiento.insertar(r_con);
        }        
        this.actualizarSaldoDebeHaber();
        
    }
    
    public void borrarCampos(){
        jTextField2.setText(renglon+"");
        jTextField3.setText("");
        jTextField3.requestFocus();
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true);        
    }
    
    private void borrarCamposAstoBasicos(){
        jTextField2.setText(renglon+"");
        jTextField3.setText("");
        jTextField3.requestFocus();
        jTextField4.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true); 
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        r_con.Connection();
        this.inicializarTabla();
        int numAsiento=getNumeroAsiento();
        jTextField1.setText(numAsiento+"");
        SimpleDateFormat formatEntrada = new SimpleDateFormat("dd/MM/yyyy"); 
        Date fechaEntrada = new Date(); 
        String fecha = formatEntrada.format(fechaEntrada);  
        campoFecha.setText(fecha);        
        renglon=1;
        jTextField9.setText(0+"");
        jTextField10.setText(0+"");
        jTextField11.setText(0+"");
        campoFecha.requestFocus();
        campoFecha.select(0,0);
        this.habilitarPanel1(true);
        r_con.cierraConexion();
        habilitarRadioButtons(false);
        jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void habilitarRadioButtons(boolean valor){
        jRadioButton1.setEnabled(valor);
        jRadioButton2.setEnabled(valor);
        jRadioButton3.setEnabled(valor);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        if(esCarga){
            jButton2.setEnabled(true);
            jButton5.setText("Abandonar Asiento");
            Asiento asiento=new Asiento();
            asiento.setOkCarga(r_con, Integer.parseInt(jTextField1.getText()),0);
        }
        campoFecha1.setText(campoFecha.getText());
        campoFecha2.setText(campoFecha.getText());
        habilitarPanel1(false);
        habilitarPanel2(true);
        jTextField3.requestFocus();                      
        jTextField2.setText(renglon+"");        
        jTable1.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * Habilita los radioButtons segun la fecha elegida, si la fechaContable
     * es del mismo dia a la fecha de apertura o a la fecha de cierre o ninguna
     */
    private void habilitarTipo(){
        if(fecha.menorFechas(campoFecha.getText(), fechaInicio)==0){
            jRadioButton1.setEnabled(true);
            jRadioButton2.setEnabled(true);
            jRadioButton1.setSelected(true);
        }
        else{
            if(fecha.menorFechas(campoFecha.getText(), fechaCierre)==0){
                jRadioButton2.setEnabled(true);
                jRadioButton3.setEnabled(true);
                jRadioButton2.setSelected(true);
            }
            else{
                jRadioButton2.setEnabled(true);
                jRadioButton2.setSelected(true);
            }            
        }                
    }
    
        
    public void generarAyuda(){
        mensajeError(" ");
        //GUI_Ayuda_PC np=new GUI_Ayuda_PC(usuario,r_con,jTextField3,jTextField4,this); 
        GUI_Ayuda_PC np=new GUI_Ayuda_PC(usuario,r_con,this);
        //lo centro respecto a x
        int x = (this.getDesktopPane().getWidth() / 2) - np.getWidth() / 2;
        int y = (this.getDesktopPane().getHeight() / 2) - np.getHeight() / 2;
        np.setLocation(x, y);        
        //lo hago visible, lo agrego al DesktopPanel, hago foco.
        np.setVisible(true);
        this.getDesktopPane().add(np);
        try {                
            np.setSelected(true);            
         } 
        catch (PropertyVetoException ex) {
            Logger.getLogger(GUI_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        np.moveToFront();
        np.requestFocus();         
    }
    
    
    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost

      boolean es_componente=false;
      //voy a preguntar si la componente que me saco el foco es algun campo del panel de datos de asientos
      //if (evt.getOppositeComponent()!=null){
        int i=0;        
        Component[] components = jPanel3.getComponents();
        while ((!es_componente)&&(i<components.length)){
            if (components[i]==evt.getOppositeComponent()){
                es_componente=true;
            }
            i++;
        }
      //}
      
      if(es_componente){
            String nroCuenta=jTextField3.getText();
            if(!nroCuenta.equals("")){            
                cuenta=obtenerCuenta(nroCuenta);            
                if(cuenta!=null){
                    if(esImputable(nroCuenta+"")){  
                        jTextField4.setText(cuenta.getNombre_C());
                        jTextField4.nextFocus();
                        mensajeError(" ");
                    }               
                    else{
                            mensajeError("La cuenta seleccionada no es imputable.");
                            jTextField3.requestFocus();
                        }
                    }            
                else{
                    jTextField3.requestFocus();
                    generarAyuda();                   
                }            
            }
            else{           
                mensajeError("El campo numero de cuenta esta vacio, debe ingresar un valor");
                jTextField3.requestFocus();
            }
      }
      else{
          mensajeError(" ");
      }
    }//GEN-LAST:event_jTextField3FocusLost

    /**
     * Nos indica true si es una cuenta, false si es un titulo
     * @param nroCuenta
     * @return true si es cuenta, false si es titulo
     */
    private boolean esImputable(String nroCuenta){
        if(!nroCuenta.equals("")){            
            cuenta=obtenerCuenta(nroCuenta+"");
            return cuenta.isImputable_C();
        }        
        else
            return false;
    }
    
    
    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        jTextField4.setText("");
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F1){            
            generarAyuda();
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        // TODO add your handling code here:    
        if ((evt.getOppositeComponent()!=jTextField3) && 
            (evt.getOppositeComponent()!=campoFecha1) &&
            (evt.getOppositeComponent()!=campoFecha2)){
        
            if(!jTextField7.getText().equals("")){
                Validaciones v = new Validaciones();
                if (v.isFloat(jTextField7.getText())){
                    if (Float.parseFloat(jTextField7.getText())>=0){
                        mensajeError(" ");
                        jTextField8.setText("");
                        jTextField8.setEnabled(false);
                        jTextField8.nextFocus();
                    }
                    else{
                        mensajeError("El saldo al Debe es negativo.");
                        jTextField7.requestFocus();
                        jTextField7.selectAll();
                    }
                }
                else{
                    mensajeError("El saldo al Debe no es un valor numérico.");
                    jTextField7.requestFocus();
                    jTextField7.selectAll();
                }            
            }
            else{
                mensajeError(" ");
                jTextField8.setEnabled(true); 
                jTextField8.requestFocus();
            }
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField8FocusLost
        // TODO add your handling code here:
        if ((evt.getOppositeComponent()!=jTextField3) && 
            (evt.getOppositeComponent()!=campoFecha1) &&
            (evt.getOppositeComponent()!=campoFecha2)){
            if(!jTextField8.getText().equals("")){
                Validaciones v = new Validaciones();
                if (v.isFloat(jTextField8.getText())){
                    if (Float.parseFloat(jTextField8.getText())>=0){
                        mensajeError(" "); 
                        jTextField7.setText("");
                        jTextField7.setEnabled(false);
                        jTextField8.nextFocus();
                    }
                    else{
                        mensajeError("El saldo al Haber es negativo.");
                        jTextField8.requestFocus();
                        jTextField8.selectAll();
                    }
                }
                else{
                    mensajeError("El saldo al Haber no es un valor numérico.");
                    jTextField8.requestFocus();
                    jTextField8.selectAll();
                }            
            }
            else{
                mensajeError(" "); 
                jTextField7.setEnabled(true);
                jTextField7.requestFocus();
            }
        }    
    }//GEN-LAST:event_jTextField8FocusLost

    private void campoFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFechaFocusLost
        // TODO add your handling code here:                        
            if((!fechaInicio.equals(""))&&(!fechaCierre.equals(""))){
                if (fecha.isFechaValida(campoFecha.getText())){
                    if(fecha.fechaEntreFechas(campoFecha.getText(), fechaDiario, fechaCierre)){
                        mensajeError(" ");            
                        habilitarTipo();
                        jPanel1.nextFocus();
                    }
                    else{
                        mensajeError("La fecha no se encuentra entre la ultima impresion del diario y la fecha de cierre.");
                        campoFecha.requestFocus();
                    }
                }
                else{
                     mensajeError("La Fecha ingresada no se reconoce como valida.");
                     campoFecha.requestFocus();
                }
            }
    }//GEN-LAST:event_campoFechaFocusLost

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        //jTextField4.requestFocus();
        //jTextField4.nextFocus();
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void campoFecha1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFecha1FocusLost
        if ((evt.getOppositeComponent()!=jTextField3)){
            if (!fecha.isFechaValida(campoFecha1.getText())){
                mensajeError("La Fecha ingresada no se reconoce como valida.");  
                campoFecha1.requestFocus();
            }
            else{
                if ((evt.getOppositeComponent()!=campoFecha2)){
                    mensajeError(" ");
                }
            }
        }
    }//GEN-LAST:event_campoFecha1FocusLost

    private void campoFecha2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFecha2FocusLost
       if ((evt.getOppositeComponent()!=jTextField3)){
            if (fecha.isFechaValida(campoFecha2.getText())){
                if(fecha.menorFechas(campoFecha1.getText(), campoFecha2.getText())!=1){                               
                    if (evt.getOppositeComponent()!=campoFecha1){    
                        mensajeError(" ");
                    }
                }
                else{
                    campoFecha2.requestFocus();
                    mensajeError("La fecha ingresada debe ser menor que la fecha de operacion");
                }
            }
            else{
                 mensajeError("La Fecha ingresada no se reconoce como valida.");
                 campoFecha2.requestFocus();
            }
        }
    }//GEN-LAST:event_campoFecha2FocusLost

    private void campoFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFechaFocusGained
        // TODO add your handling code here:
        habilitarRadioButtons(false);
        
    }//GEN-LAST:event_campoFechaFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float saldo=Float.parseFloat(jTextField10.getText());
        if(saldo==0){                    
            for(int i=0;i<modelo.getRowCount();i++){
                r_con.Connection();
                int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=Integer.parseInt(modelo.getValueAt(i, 0).toString());               
                String cadena="update borrador_asientos set ba_ok_carga=1 where ba_nro_asiento="+numAsiento+" and ba_nro_renglon="+numRenglon;                
                this.habilitarPanel1(false);
                this.habilitarPanel2(false);
                r_con.ActualizarSinCartel(cadena);                               
            }
            if (modelo.getRowCount()>0){
                JOptionPane.showMessageDialog(null,"El asiento fue cargado correctamente");    
            }
            else{
                JOptionPane.showMessageDialog(null,"Realice una nueva Carga"); 
            }            
            this.habilitarPanel2(false);
            jButton6.setEnabled(true);
            jButton5.setEnabled(true);
            boton7.setEnabled(false);
            jButton1.setText("Cancelar");
            this.inicializarTabla();
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"El asiento que usted intenta registrar no balancea");
        }
        jTextField9.setText(0+"");
        jTextField10.setText(0+"");
        jTextField11.setText(0+"");
        r_con.cierraConexion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int rta=0;
        if(modelo.getRowCount()!=0){
        rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Retomar Asiento", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){        // TODO add your handling code here:
                habilitarPanelCarga1(true);        
                this.inicializarTabla();                
                esCarga=true;
                campoFecha.setText("");
                campoFecha1.setText("");
                campoFecha2.setText("");
            }
        }
        else
        {        
            habilitarPanelCarga1(true);        
            this.inicializarTabla();
            esCarga=true;
            campoFecha.setText("");
            campoFecha1.setText("");
            campoFecha2.setText("");
        }
        jButton5.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
        try{
            if(esCarga){
                if((jTextField1==null)||(jTextField1.getText().equals("")))
                    jTextField1.requestFocus();
                else
                {
                int numAsiento=Integer.parseInt(jTextField1.getText());
                r_con.Connection();

                    ResultSet rs=r_con.Consultar("select ba_nro_asiento,ba_ok_registrado from borrador_asientos where ba_nro_asiento="+numAsiento);
                    if(rs.next()){
                        if(!rs.getBoolean(2)){                        
                            cargarCampos(rs.getInt(1));
                            jButton3.setEnabled(true);
                            mensajeError(" ");
                        }
                        else
                        {
                            deshabilitarCampos();
                            jTextField1.requestFocus();
                            mensajeError("El asiento ya se encuentra registrado");
                        }
                    }
                    else
                    {
                        deshabilitarCampos();
                        jTextField1.requestFocus();
                        mensajeError("El asiento ingresado no existe");                
                    }            
                    r_con.cierraConexion();
                }
            }
        }
        catch(Exception e){
            r_con.cierraConexion();
            System.out.println(e.getMessage());
        }        
    }//GEN-LAST:event_jTextField1FocusLost

    private void campoFecha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFecha1FocusGained
        campoFecha1.select(0,0);      
    }//GEN-LAST:event_campoFecha1FocusGained

    private void campoFecha2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFecha2FocusGained
        campoFecha2.select(0,0);    
    }//GEN-LAST:event_campoFecha2FocusGained

    private void jRadioButton1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton1FocusLost
        // TODO add your handling code here:
        jButton3.requestFocus();
    }//GEN-LAST:event_jRadioButton1FocusLost

    private void jRadioButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton2FocusLost
        // TODO add your handling code here:
        jButton3.requestFocus();
    }//GEN-LAST:event_jRadioButton2FocusLost

    private void jRadioButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButton3FocusLost
        // TODO add your handling code here:
        jButton3.requestFocus();
    }//GEN-LAST:event_jRadioButton3FocusLost


    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:        
        if(jTable1.isEnabled()){
            if(evt.getClickCount()==2){            
                int fila=jTable1.getSelectedRow();
            //"Renglon","Nro. Cuenta","Fecha Oper.","Fecha Vto.","Nro Comprobante","Leyenda","Debe","Haber"
                int numRenglon=Integer.parseInt((String)modelo.getValueAt(fila, 0));
                int numCuenta=Integer.parseInt((String)modelo.getValueAt(fila, 1));
                String fechaOp=(String)modelo.getValueAt(fila, 2);
                String fechaVto=(String)modelo.getValueAt(fila, 3);
                String comprobante=(String)modelo.getValueAt(fila, 4);
                String leyenda=(String)modelo.getValueAt(fila, 5);
                BigDecimal debe=convertirEnBigDecimal((String)modelo.getValueAt(fila, 6));
                BigDecimal haber=convertirEnBigDecimal((String)modelo.getValueAt(fila, 7));

                jTextField2.setText(numRenglon+"");
                jTextField3.setText(numCuenta+"");

                jTextField3.requestFocus();jTextField2.requestFocus();jTextField3.requestFocus();
                campoFecha1.setText(fecha.convertirBarras(fechaOp));
                campoFecha2.setText(fecha.convertirBarras(fechaVto));
                jTextField5.setText(comprobante);
                jTextField6.setText(leyenda);
                jTextField7.setText("");
                jTextField8.setText("");
                if(debe.floatValue()==0)
                    jTextField8.setText(haber+"");
                else
                    jTextField7.setText(debe+"");
                habilitarPanel2(true);
                boton7.setEnabled(true);
                jButton4.setText("Modificar");
            }               
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!jTextField7.isEnabled()){
            jTextField7.setText("");
        }
        if(!jTextField8.isEnabled()){
            jTextField8.setText("");
        }        
        if(jButton4.getText().equals("Confirmar")){
            if(controlarCampos()){
                jButton2.setEnabled(true);
                jButton1.setText("Abandonar Asiento");
                cargarTabla();
                borrarCamposAstoBasicos();
                mensajeError(" ");
            }
            else
            {
                mensajeError("Debe completar todos los campos");
            }
        }
        else
        {
            if(controlarCampos()){
                jButton4.setText("Confirmar");
                actualizarTabla();
                mensajeError(" ");
                borrarCamposAstoBasicos();                
            }
            else
                mensajeError("Debe completar todos los campos");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        boton7.setEnabled(false);
        int rta=JOptionPane.showConfirmDialog(null,"El asiento sera eliminado. ¿Desea continuar?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);                            
            if (rta==JOptionPane.YES_OPTION){
                int numAsiento=Integer.parseInt(jTextField1.getText());
                int numRenglon=Integer.parseInt(jTextField2.getText());
                modelo.removeRow(numRenglon-1);
                r_con.Connection();
                r_con.ActualizarSinCartel("delete from borrador_asientos where ba_nro_asiento="+numAsiento);
                renombrarTabla();
            }
            else
                boton7.setEnabled(true);
            jButton4.setText("Confirmar");
    }//GEN-LAST:event_boton7ActionPerformed

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        // TODO add your handling code here:
        jTextField6.requestFocus();
    }//GEN-LAST:event_jTextField5FocusLost

    private void actualizarTabla(){
        int numRenglon=(Integer.parseInt(jTextField2.getText()))-1;
            
            int ren=numRenglon+1;
            modelo.setValueAt(ren+"",numRenglon , 0);
            modelo.setValueAt(Integer.parseInt(jTextField3.getText())+"",numRenglon , 1);
            modelo.setValueAt(campoFecha1.getText(),numRenglon , 2);
            modelo.setValueAt(campoFecha2.getText(),numRenglon , 3);
            modelo.setValueAt(jTextField5.getText(),numRenglon , 4);
            modelo.setValueAt(jTextField6.getText(),numRenglon , 5);
            BigDecimal d=new BigDecimal(0);
            BigDecimal h=new BigDecimal(0);
            if(jTextField7.isEnabled()){
                d=convertirEnBigDecimal(Float.parseFloat(jTextField7.getText())+"");
            }
            else
            {
                h=convertirEnBigDecimal(Float.parseFloat(jTextField8.getText())+"");
            }    
            modelo.setValueAt(d+"",numRenglon , 6);
            modelo.setValueAt(h+"",numRenglon , 7);
            int numAsiento=Integer.parseInt(jTextField1.getText());
            r_con.Connection();
            //Renglon","Nro. Cuenta","Fecha Oper.","Fecha Vto.","Nro Comprobante","Leyenda","Debe","Haber
            r_con.ActualizarSinCartel("update borrador_asientos set ba_fecha_operacion='"+campoFecha1.getText()+
                                      "' ,ba_fecha_vencimiento='"+campoFecha2.getText()+
                                      "' ,ba_nro_comprobante='"+jTextField5.getText()+
                                      "' ,ba_leyenda='"+jTextField6.getText()+
                                      "' ,ba_debe="+d+" ,ba_haber="+h+" where ba_nro_asiento="+numAsiento+" and ba_nro_renglon="+ren);                                                  
            r_con.cierraConexion();
            this.actualizarSaldoDebeHaber();
    }
    
    
    private void deshabilitarCampos(){
        this.inicializarTabla();
        campoFecha.setText("");
        habilitarRadioButtons(false);                
//        jButton3.setEnabled(false);
        jTextField3.setText("");                
        jTextField4.setText("");
        campoFecha1.setText("");
        campoFecha2.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
    }
    
    private void cargarCampos(int numAsiento){
        try {
            r_con.Connection();
            ResultSet rs=r_con.Consultar("select * from borrador_asientos where ba_nro_asiento="+numAsiento);
            Asiento asiento=null;
            renglon=0;
            BigDecimal debeTotal=new BigDecimal(0);
            BigDecimal haberTotal=new BigDecimal(0);
            while(rs.next()){
                renglon++;
                    asiento=new Asiento(rs.getInt(1),rs.getInt(2),rs.getDate(3).toString(),
                                            rs.getDate(6).toString(),rs.getDate(7).toString(),
                                            rs.getString(4),rs.getInt(5),rs.getString(8),
                                            rs.getString(9),rs.getFloat(10),rs.getFloat(11),
                                            rs.getBoolean(12),rs.getBoolean(13));
                modelo.addRow(asiento.getRenglonModelo());
                jTable1.setModel(modelo);           
                BigDecimal asDebe=convertirEnBigDecimal(asiento.getDebe()+"");
                debeTotal=sumarBigDecimal(debeTotal+"",asDebe+"");
                BigDecimal asHaber=convertirEnBigDecimal(asiento.getHaber()+"");
                haberTotal=sumarBigDecimal(haberTotal+"",asHaber+"");
            }
            jTextField9.setText(debeTotal+"");
            jTextField11.setText(haberTotal+"");
            BigDecimal saldo=sumarBigDecimal(debeTotal+"","-"+haberTotal);
            jTextField10.setText(saldo+"");
            if(asiento!=null){                                                             
                campoFecha.setText(fecha.convertirBarras(asiento.getFecha_contable()));                
                jTextField2.setText(++renglon+"");
                if(asiento.getTipo().equals("Asiento Apertura")){
                    jRadioButton1.setSelected(true);
                }
                else{
                    if(asiento.getTipo().equals("Asiento Normal")){
                        jRadioButton2.setSelected(true);
                    }
                    else{
                        jRadioButton3.setSelected(true);
                    }                        
                }
            }
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
        
    private void habilitarPanelCarga1(boolean valor){
        campoFecha.setEnabled(!valor);
        campoFecha.setEditable(!valor);
        jTextField1.setEnabled(valor);
        jTextField1.setEditable(valor);
        jButton3.setEnabled(valor);
        jTextField1.requestFocus();
        this.habilitarRadioButtons(!valor);
        
    }
    
    private void habilitarPanel1(boolean valor){
        campoFecha.setEnabled(valor);
        jTextField1.setEnabled(valor);
        this.habilitarRadioButtons(valor);
        jButton3.setEnabled(valor);
    }
    
    private void habilitarPanel2(boolean valor){
        jTextField2.setEnabled(valor);
        jTextField3.setEnabled(valor);
        jTextField4.setEnabled(valor);
        jTextField5.setEnabled(valor);
        jTextField6.setEnabled(valor);
        jTextField7.setEnabled(valor);
        jTextField8.setEnabled(valor);
        campoFecha1.setEnabled(valor);
        campoFecha2.setEnabled(valor); 
        boton7.setEnabled(!valor);
        jButton4.setEnabled(valor);
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField campoFecha;
    private javax.swing.JFormattedTextField campoFecha1;
    private javax.swing.JFormattedTextField campoFecha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables


    private int getNumeroAsiento() {
        int asiento=-1;
        try {                        
            r_con.Connection();
            ResultSet rs=r_con.Consultar("select max(ba_nro_asiento) from "+nameTabla);
            rs.next();
            asiento=rs.getInt(1)+1;
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);            
        }
        return asiento;
    }

    private Cuenta obtenerCuenta(String nroCta) {
        Cuenta aux=null;
        try {            
            r_con.Connection();
            int nroCuenta=Integer.parseInt(nroCta);
            ResultSet rs=r_con.Consultar("select * from plan_cuentas where pc_nro_cuenta="+nroCuenta);
            if(rs.next()){
                aux=new Cuenta();
                aux.setCodigo_PC(rs.getString(1));
                aux.setNumero_C(rs.getInt(2));
                aux.setNombre_C(rs.getString(3));
                aux.setImputable_C(rs.getBoolean(4));
                aux.setNumero_Padre_C(rs.getInt(5));
            }
            r_con.cierraConexion();
        } catch (SQLException ex) {
            r_con.cierraConexion();
            Logger.getLogger(GUI_Cargar_Asiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        return aux;
    }



    private void inicializarTabla() {        
        modelo=new DefaultTableModelAsientos();
        String [] columnas= {"Renglon","Nro. Cuenta","Fecha Oper.","Fecha Vto.","Nro Comprobante","Leyenda","Debe","Haber"};
        modelo.setColumnIdentifiers(columnas); 
        jTable1.setModel(modelo);
        
    }

    private void mensajeError(String msj) {
        jLabel17.setText(msj); 
       
    }
    
    /**
     * Nos retorna el numero del tipo, segun el radio button seleccionado
     * @return 
     */
    private String getTipo(){
        if(jRadioButton1.isSelected())
            return "Asiento Apertura";
        if(jRadioButton2.isSelected())
            return "Asiento Normal";
        if(jRadioButton3.isSelected())
            return "Asiento Cierre";
        return "";
    }
    
    private void cargarTabla(){
        int num_asiento=Integer.parseInt(jTextField1.getText());
        String tipo=getTipo();
        String fecha_contabilidad=campoFecha.getText();
        int num_cuenta=Integer.parseInt(jTextField3.getText());
        String fecha_operacion=campoFecha1.getText();
        String fecha_vencimiento=campoFecha2.getText();
        String comprobante=jTextField5.getText();
        String leyenda=jTextField6.getText();
        BigDecimal debe,haber;        
        debe=new BigDecimal(0);
        haber=new BigDecimal(0);
        if((jTextField7.isEnabled())&&(!jTextField7.equals(""))){
            haber=new BigDecimal(0);
            float d=Float.parseFloat(jTextField7.getText());
            debe=convertirEnBigDecimal(d+"");
        }
        else
        {
            if((jTextField8.isEnabled())&&(!jTextField8.equals(""))){
                debe=new BigDecimal(0);
                float h=Float.parseFloat(jTextField8.getText());
                haber=convertirEnBigDecimal(h+"");
            }
        }        
        BigDecimal debeTotal=convertirEnBigDecimal(jTextField9.getText());
        debeTotal=sumarBigDecimal(debeTotal+"",debe+"");
        BigDecimal haberTotal=convertirEnBigDecimal(jTextField11.getText());        
        haberTotal=sumarBigDecimal(haberTotal+"",haber+"");
        BigDecimal saldo=sumarBigDecimal(haberTotal+"","-"+debeTotal);
        jTextField9.setText(debeTotal+"");
        jTextField11.setText(haberTotal+"");
        jTextField10.setText(saldo+"");
        
        Asiento asiento=new Asiento(num_asiento,renglon,fecha_contabilidad,fecha_operacion,fecha_vencimiento,tipo,num_cuenta,comprobante,leyenda,debe.floatValue(),haber.floatValue(),false,false);
        asiento.insertar(r_con);
        
        String []aux_modelo={renglon+"",num_cuenta+"",fecha_operacion,fecha_vencimiento,comprobante,leyenda,debe+"",haber+""};
        modelo.addRow(aux_modelo);  
        jTable1.setModel(modelo);
        renglon++;
    }
    
    /**
     * Nos controla los campos de Leyenda y Comprobante
     * @return true en caso de que ambos esten completos false de lo contrario
     */
    private boolean controlarCampos(){
        if((!jTextField5.getText().equals(""))&&(!jTextField6.getText().equals("")))
            return true;
        else
            return false;
    }
    
    /**
     * Recorre la tabla y recalcula el debe el haber y saldo 
     */
    public void actualizarSaldoDebeHaber(){
        BigDecimal debe=new BigDecimal(0);
        BigDecimal haber=new BigDecimal(0);
        String dAux;
        String hAux;
        for(int i=0;i<modelo.getRowCount();i++){
            dAux=modelo.getValueAt(i, 6)+"";
            hAux=modelo.getValueAt(i, 7)+"";
            debe=sumarBigDecimal(debe+"",dAux);
            haber=sumarBigDecimal(haber+"",hAux);
        }
        jTextField9.setText(debe+"");        
        jTextField11.setText(haber+"");
        jTextField10.setText(sumarBigDecimal(debe+"","-"+haber)+"");
    }
    
    private BigDecimal sumarBigDecimal(String num1,String num2){        
        float num1Float=Float.parseFloat(num1);
        float num2Float=Float.parseFloat(num2);
        String formato1=new DecimalFormat("0.00").format(num1Float);
        String formato2=new DecimalFormat("0.00").format(num2Float);
        formato1=formato1.replace(',', '.');
        formato2=formato2.replace(',', '.');        
        BigDecimal num1BigD=new BigDecimal(formato1);
        BigDecimal num2BigD=new BigDecimal(formato2);
        BigDecimal suma=num1BigD.add(num2BigD);        
        return suma;
    }
    
    private BigDecimal convertirEnBigDecimal(String num){
        float num1=Float.parseFloat(num);
        String formato=new DecimalFormat("0.00").format(num1);
        formato=formato.replace(',','.');
        BigDecimal bigNum=new BigDecimal(formato);
        return bigNum;
    }
    
        
    
}
