/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main_Conta.java
 *
 * Created on 21-ago-2011, 15:23:41
 */

package _Pruebas;

import Clases_Auxiliares.Conexion;
import Objetos.Cuenta;
import Objetos.Usuario;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Wilfo
 */
public class Main_Conta extends javax.swing.JFrame {

    /** Creates new form Main_Conta */
    public static int intIdUser=0;
    Vector<CLS_ITEM_CONTA> vecChildren = new Vector<CLS_ITEM_CONTA>();
    CLS_CONTABILIDAD clsConta;
    int bcount=0;
    DefaultTreeModel modelo1 = null;
    DefaultMutableTreeNode root1 = null;
    DefaultMutableTreeNode parent1 = null;
    DefaultMutableTreeNode childnode = null;
    int posLoad=0;
    
    private Conexion r_con;
    private Usuario usr;
    
    
    public Main_Conta(Usuario u, Conexion con) {
        usr = u;
        r_con=con;
        clsConta=new CLS_CONTABILIDAD(usr,r_con);
        recarga();
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTreeConta = new javax.swing.JTree();
        JDKConta = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JTreeConta.setForeground(new java.awt.Color(255, 255, 255));
        JTreeConta.setModel(modelo1);
        JTreeConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTreeContaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTreeConta);

        JDKConta.setBackground(new java.awt.Color(91, 141, 191));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JDKConta, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JDKConta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargarArbol();
        cargarConta();       
    }//GEN-LAST:event_formWindowOpened

    private void JTreeContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTreeContaMouseClicked
      
        
    }//GEN-LAST:event_JTreeContaMouseClicked

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane JDKConta;
    public static javax.swing.JTree JTreeConta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    public void cargarArbol() {
        int count = 0;
        int aux = 1;
        int entre = 0;
        Enumeration e = root1.breadthFirstEnumeration();
        while (e.hasMoreElements()) {
            parent1 = (DefaultMutableTreeNode) e.nextElement();
            if (count >= aux) {
                CLS_ITEM_CONTA objChildren = (CLS_ITEM_CONTA) parent1.getUserObject();
                //consigo los hijos de idparent
                System.out.println(objChildren.Descripcion);
                vecChildren = clsConta.getChildrenC(objChildren.Id);
                for (int k = 0; k < vecChildren.size(); k++) {
                    CLS_ITEM_CONTA hijo = (CLS_ITEM_CONTA) vecChildren.get(k);
                    //hijo.setDescrip(hijo.getCodigo_PC()+"-"+hijo.getNombre_C());
                    System.out.println("        -> "+hijo.Descripcion);
                    childnode = new DefaultMutableTreeNode(hijo);
                    modelo1.insertNodeInto(childnode, parent1, parent1.getChildCount());
                }
            }
            //Pregunto si llego al fin.
            if (e.hasMoreElements() == false) {
                
                int toEle = totalElementos(root1.breadthFirstEnumeration());
                System.out.println(">>> ENTRE EN HASMORE toEle: "+toEle+" bcount: "+bcount+" count: "+count);
                if (bcount < toEle) {
                    System.out.println("-----------------");
                    if (entre==0){
                        aux = count;
                        count = -2;
                        entre+=1;
                    }
                    else{
                        aux = count+1;
                        count = -2;
                    }
                    e = root1.breadthFirstEnumeration();
                    bcount = toEle;
                } else {
//                     JOptionPane.showMessageDialog(this, "Ya no hay mas hijos");
                    break;
                }
            }
            count++;
        }

    }


   public void recarga() {
        r_con.Connection();
        CLS_ITEM_CONTA obj = (CLS_ITEM_CONTA) clsConta.getChildrenC("0").get(0);
        root1 = new DefaultMutableTreeNode(obj);
        modelo1 = new DefaultTreeModel(root1);
        Enumeration e = root1.breadthFirstEnumeration();
        parent1 = (DefaultMutableTreeNode) e.nextElement();
        CLS_ITEM_CONTA objChildren = (CLS_ITEM_CONTA) parent1.getUserObject();
//consigo los hijos de idparent
        vecChildren = clsConta.getChildrenC(objChildren.Id);

        for (int k = 0; k < vecChildren.size(); k++) {
            bcount++;
            CLS_ITEM_CONTA hijo = (CLS_ITEM_CONTA) vecChildren.get(k);
            modelo1.insertNodeInto(new DefaultMutableTreeNode(hijo), parent1, parent1.getChildCount());
        }
//        TreeCuenta.setModel(modelo1);
        r_con.cierraConexion();
    }

   public int totalElementos(Enumeration e) {
        int cont = 0;
        while (e.hasMoreElements()) {
            e.nextElement();
            cont++;
        }
        return cont;
    }

   public void LoadDinamico(String id){
     JTreeConta.setModel(null);
     //JTreeConta.setModel(clsConta.cargarArbol(id));
   }
   void cargarConta(){
        //Plan_Modificar objNuevo=new Plan_Modificar();
        //Main_Conta.JDKConta.add(objNuevo);
        //objNuevo.toFront();
        //objNuevo.setVisible(true);
   }
}
